//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemoDavi.Svr_datamdavi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="listusu", Namespace="http://schemas.datacontract.org/2004/07/Demodavi")]
    [System.SerializableAttribute()]
    public partial class listusu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable usuardatamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable usuardatam {
            get {
                return this.usuardatamField;
            }
            set {
                if ((object.ReferenceEquals(this.usuardatamField, value) != true)) {
                    this.usuardatamField = value;
                    this.RaisePropertyChanged("usuardatam");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="listusuparami", Namespace="http://schemas.datacontract.org/2004/07/Demodavi")]
    [System.SerializableAttribute()]
    public partial class listusuparami : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable usuardatamparamiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable usuardatamparami {
            get {
                return this.usuardatamparamiField;
            }
            set {
                if ((object.ReferenceEquals(this.usuardatamparamiField, value) != true)) {
                    this.usuardatamparamiField = value;
                    this.RaisePropertyChanged("usuardatamparami");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Svr_datamdavi.ISvrdatam")]
    public interface ISvrdatam {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvrdatam/insercion", ReplyAction="http://tempuri.org/ISvrdatam/insercionResponse")]
        string insercion(int opt, int idusu, string nombre, string fecnaci, string sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvrdatam/insercion", ReplyAction="http://tempuri.org/ISvrdatam/insercionResponse")]
        System.Threading.Tasks.Task<string> insercionAsync(int opt, int idusu, string nombre, string fecnaci, string sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvrdatam/Dtusuar", ReplyAction="http://tempuri.org/ISvrdatam/DtusuarResponse")]
        MvcDemoDavi.Svr_datamdavi.listusu Dtusuar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvrdatam/Dtusuar", ReplyAction="http://tempuri.org/ISvrdatam/DtusuarResponse")]
        System.Threading.Tasks.Task<MvcDemoDavi.Svr_datamdavi.listusu> DtusuarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvrdatam/Dtusuarparami", ReplyAction="http://tempuri.org/ISvrdatam/DtusuarparamiResponse")]
        MvcDemoDavi.Svr_datamdavi.listusuparami Dtusuarparami(int numi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvrdatam/Dtusuarparami", ReplyAction="http://tempuri.org/ISvrdatam/DtusuarparamiResponse")]
        System.Threading.Tasks.Task<MvcDemoDavi.Svr_datamdavi.listusuparami> DtusuarparamiAsync(int numi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvrdatamChannel : MvcDemoDavi.Svr_datamdavi.ISvrdatam, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvrdatamClient : System.ServiceModel.ClientBase<MvcDemoDavi.Svr_datamdavi.ISvrdatam>, MvcDemoDavi.Svr_datamdavi.ISvrdatam {
        
        public SvrdatamClient() {
        }
        
        public SvrdatamClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvrdatamClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvrdatamClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvrdatamClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string insercion(int opt, int idusu, string nombre, string fecnaci, string sexo) {
            return base.Channel.insercion(opt, idusu, nombre, fecnaci, sexo);
        }
        
        public System.Threading.Tasks.Task<string> insercionAsync(int opt, int idusu, string nombre, string fecnaci, string sexo) {
            return base.Channel.insercionAsync(opt, idusu, nombre, fecnaci, sexo);
        }
        
        public MvcDemoDavi.Svr_datamdavi.listusu Dtusuar() {
            return base.Channel.Dtusuar();
        }
        
        public System.Threading.Tasks.Task<MvcDemoDavi.Svr_datamdavi.listusu> DtusuarAsync() {
            return base.Channel.DtusuarAsync();
        }
        
        public MvcDemoDavi.Svr_datamdavi.listusuparami Dtusuarparami(int numi) {
            return base.Channel.Dtusuarparami(numi);
        }
        
        public System.Threading.Tasks.Task<MvcDemoDavi.Svr_datamdavi.listusuparami> DtusuarparamiAsync(int numi) {
            return base.Channel.DtusuarparamiAsync(numi);
        }
    }
}
